### ISSUE TITLE
Something not working

### ISSUE THREAD

**Issue by PhilippKorn** [lilyinstarlight/vim-sonic-pi#1]
Hi, when my sonic-pi-cli.py Server is running, I'm still not able to use it from within vim. Maybe I misse something but neither of the commands are working.... :/

I installed with Vim-Plug and my vimrc settings are:

let g:sonicpi_command = 'sonic-pi-tool'
let g:sonicpi_send = 'eval-stdin'
let g:sonicpi_stop = 'stop'
let g:vim_redraw = 1

How can I actually use the plugin now?

**Comment by lilyinstarlight** [comment]
Hello! Are you able to use `sonic-pi-tool` as a command from a terminal and if not, what command do you use to start the server?

**Comment by PhilippKorn** [comment]
hey,

to start the server I'm using 

```bash
sonic-pi-tool.py start-server
```

which is working from the command line. Do I have to change my vim config? 
I'm sure to be missing something :/

**Comment by lilyinstarlight** [comment]
Okay, it looks like you may only need to adjust the command the plugin is trying to call (the `g:sonicpi_command` setting), since the tool is called `sonic-pi-tool.py` on your system

```vim
let g:sonicpi_command = 'sonic-pi-tool.py'
```

Does making that change help?

**Comment by PhilippKorn** [comment]
I made the change but still it does not seem to work. Maybe I'm still a bit confused with running from within vim. Leader key ist not working. 

Starting it from the console from within vim with

```bash
!sonic-py-tool.py eval-file test.rb
```
works finde but thats not how it is supposed to be used right?

**Comment by lilyinstarlight** [comment]
I had a typo in my last comment, and the proper option name should be:

```vim
let g:sonicpi_command = 'sonic-pi-tool.py'
```

Additionally, could you confirm that the file is opened with the Ruby file type after the server is started? (typing `:set ft` and enter should show it)

Edit: And yeah, you should not need to manually run commands via `!` for the plugin to work

**Comment by PhilippKorn** [comment]
To give you a little more info:

After the server is started it shows: 

This is Sonic Pi v3.3.1 running on osx with ruby version 3.0.0 with api 3.0.0.
Sonic Pi Server successfully booted.

```:set ft``` gives ```filetype=ruby```

thank you for your help!

**Comment by lilyinstarlight** [comment]
I typo'd the option twice because I copied it and forgot to fix it before sending...

```vim
let g:sonic_pi_command = 'sonic-pi-tool.py'
```

There's an extra underscore you might be missing in the option name (and for the other two options as well). Does changing that fix it?

**Comment by PhilippKorn** [comment]
THANK YOU! :D so simple!

**Comment by lilyinstarlight** [comment]
Awesome, I'm glad it's working for you! Let me know if you run into any other issues or feel like you're really missing some feature
